name:           Contador Assassinato Marielle Franco
nickname:       contador-assassinato-marielle-franco
plugin_version: 2.2.0
baseurl:        http://lpirola.github.io/contador-assassinato-marielle-franco
highlight:      true
markdown:       kramdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
collections:
  examples:
    output: true
exclude:
  - node_modules/
